# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e18f5799784134ac33dcd89cdcacf7b062bab49c2cccd0e94e55d3be5d485226caf819c6a77af76bfccca94ffd1c1b254202d3e4c2f146e02bde72fa4a80f3e

test:
  secret_key_base: 594933705fa0a17ff0d6dd746f29f347e8fa35cb2a0ebf3f935ee148717b3f9f9bbfdf066cce501000a8e136a2580965985acc743be61849e1c7855cb534996f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
